### PR TITLE
GH-101 add import documentation.

### PR DESCRIPTION
**Pull request by danielmkn**
All documentation updates should be done through templates modifications, if the .md file is updated directly, the changes will be lost when `make doc` is running.

### CODE REVIEW

**Review by alexhung — COMMENTED** [review]
Looks ok. Have you tried using the resource template and use the resource data field to generate the import address? See `templates/resources.md[.tmpl]` in https://github.com/hashicorp/terraform-plugin-docs#conventional-paths

This way we will only need one template.

**Comment by danielmkn** [comment]
Not sure if it will be a good fit for us. I'll try, I'm curious how Import section will look like.

**Comment by danielmkn** [comment]
We can't have only one generic template. Each of them needs unique parts.

**Review by alexhung — APPROVED** [review]

**Comment by danielmkn** [comment]
Some context here, [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) doesn't support setting subcategories from the code. So it was decided to have one template per resource for now.

**Pull request merged**
